# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Demo of calling 'crc32c' functions
#'
#' @return The function is called for its side effect of printing to stdout,
#' nothing is returned
crc32cdemo <- function() {
    invisible(.Call(`_crc32cExample_crc32cdemo`))
}

